# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  version:
    name: Versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine versioning
        uses: paulhatch/semantic-version@v4.0.3
        id: versioning
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: true
      - name: Determine build version
        id: build_version
        run: |
          BUILD_NO=$((${{ github.run_number }} + 100))
          echo "::set-output name=build_no::$BUILD_NO"
      - name: Print versioning
        run: |
          echo "Version: $VERSION"
          echo "Version Tag: $VERSION_TAG"
          echo "Run No: $BUILD_NO"
        env:
          VERSION: ${{ steps.versioning.outputs.version }}
          VERSION_TAG: ${{ steps.versioning.outputs.version_tag }}
          BUILD_NO: ${{ steps.build_version.outputs.build_no }}
    outputs:
      version: ${{ steps.versioning.outputs.version }}
      version_tag: ${{ steps.versioning.outputs.version_tag }}
      build_version: ${{ steps.build_version.outputs.build_no }}
  dummy-print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Test console
        run: node --version
